name: TestFlightDeploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v1

        - name: Make shells executable
          run: |
            chmod +x ./.github/scripts/*.sh
            chmod +x ./.github/secrets/decrypt_secrets.sh

        - name: Test
          run: ./.github/scripts/test.sh
  
        - name: Install gpg
          run: brew install gpg

        - name: Setup provisioning profile
          env:
            PROFILE_DECRYPTION_KEY: ${{ secrets.PROFILE_DECRYPTION_KEY }}
            CERTIFICATE_DECRYPTION_KEY: ${{ secrets.CERTIFICATE_DECRYPTION_KEY }}
            P12_PASSPHRASE: ${{ secrets.P12_PASSPHRASE }}
          run: ./.github/secrets/decrypt_secrets.sh

      # - name: Archiving project
      #   run: |
      #     set -eo pipefail

      #     xcodebuild -project DummyCI.xcodeproj \
      #       -scheme DummyCI \
      #       -sdk iphoneos \
      #       -configuration Release \
      #       -archivePath $PWD/build/DummyCI.xcarchive \
      #       clean archive | xcpretty

      # - name: Exporting .ipa
      #   run: |
      #     set -eo pipefail

      #     xcodebuild -archivePath $PWD/build/DummyCI.xcarchive \
      #       -exportOptionsPlist ExportOptions.plist \
      #       -exportPath $PWD/build \
      #       -allowProvisioningUpdates \
      #       -exportArchive | xcpretty

      # - name: Publishing app
      #   if: success()
      #   env:
      #     APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
      #     APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
      #   run: xcrun altool --upload-app -t ios -f $PWD/build/DummyCI.ipa -u "$APPLEID_USERNAME" -p "$APPLEID_PASSWORD" --verbose
