name: TestFlightDeploy
on:
  push:
    branches:
      - main
  pull_requests:
    branches:
      - main

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v1

        - name: Make shells executable
          run: |
            chmod +x ./.github/scripts/*.sh
            chmod +x ./.github/secrets/decrypt_secrets.sh

        - name: Test
          run: ./.github/scripts/test.sh
  
        - name: Install gpg
          run: brew install gpg

        - name: Setup provisioning profile
          env:
            PROFILE_DECRYPTION_KEY: ${{ secrets.PROFILE_DECRYPTION_KEY }}
            CERTIFICATE_DECRYPTION_KEY: ${{ secrets.CERTIFICATE_DECRYPTION_KEY }}
            P12_PASSPHRASE: ${{ secrets.P12_PASSPHRASE }}
          run: ./.github/secrets/decrypt_secrets.sh

        - name: Archiving project
          run: ./.github/scripts/archive.sh
      

        - name: Exporting .ipa
          run: ./.github/scripts/export_ipa.sh

        - name: Publishing app
          if: success()
          env:
            APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
            APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
          run: ./.github/scripts/upload_app.sh
